language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6-dev
  - pypy
  - pypy3

matrix:
  allow_failures:
      - python: pypy3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdiscid0-dev

install:
  - pip install setuptools
  - pip install pkgconfig
  - pip install 'cython >= 0.15'
  # documentation specific dependencies
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install 'sphinx>=1.2,<1.3a1'; else pip install sphinx; fi
  - python setup.py build
  - python setup.py build_ext -i
  - python setup.py build_sphinx

script:
  - nosetests libdiscid/tests
