language: python
dist: bionic
addons:
  apt:
    packages:
      - libdiscid-dev
      - pkg-config

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy3

matrix:
  allow_failures:
     - python: 3.9-dev
     - python: pypy3

install:
  - pip install setuptools
  - pip install pkgconfig
  - pip install 'cython >= 0.15'
  # documentation specific dependencies
  - pip install sphinx
  - python setup.py build
  - python setup.py build_ext -i
  - python setup.py build_sphinx

script:
  - nosetests libdiscid/tests
