language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6-dev
  - pypy
  - pypy3

matrix:
  allow_failures:
      - python: pypy3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdiscid0-dev

install:
  - pip install setuptools
  - pip install pkgconfig
  - pip install 'cython >= 0.15'
  # documentation specific dependencies
  - python setup.py build
  - python setup.py build_ext -i
  - python setup.py build_sphinx

script:
  - nosetests libdiscid/tests
