language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdiscid0-dev

install:
  - pip install setuptools
  - pip install pkgconfig
  - pip install 'cython >= 0.15'
  # documentation specific dependencies
  - pip install sphinx
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - python setup.py build
  - python setup.py build_ext -i
  - python setup.py build_sphinx

script:
  - cd build/lib/
  - nosetests libdiscid/tests
